#podman compose up --build -d

services:
  frontend:
    container_name: roster-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./frontend:/home/node/app
  backend:
    container_name: roster-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 4000:4000
    volumes: 
     - ./backend:/home/node/app


